### ISSUE TITLE
Is involucro a dependency for galaxy-lib (to build containers the mulled way)?

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-lib#123]
Hi there!

Is involucro a dependency to galaxy-lib if I want to build containers with it? Is involucro being maintained? Project's last commit seem old. I was going to write a homebrew formula for involucro, but among guidelines for homebrew it says the upstream project needs to be maintained (and last commits seem very old for involucro).

Ping @bgruening 

Thanks!
Pablo

**Comment by bgruening** [comment]
Yes, it is a dependency if you want to build containers on the fly. It is maintained, but does not need updates afaik. Just a static GO tool for wrangling around with Docker.
I can add a dummy commit if this helps :)

**Comment by pcm32** [comment]
Great, thanks!

**Comment by bgruening** [comment]
@pcm32 please also note that mulled can and will download involucro if it can not be found.
