### ISSUE TITLE
Dependency on quay.io for mulled containers

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-lib#126]
Hi all,

I'm interested in using the local generation of container from bioconda packages for packages that we have in development (so that we can have a container way sooner than the package is actually accepted in conda). I'm concerned though about the strong coupling/vendor lock-in with quay.io. Would it be possible for the mulled/involucro script to leave the docker image available locally so that it can be pushed "manually" or independently to other registries that are not quay.io? I can put sometime on this, but I need to understand how constrained we are by how involucro works. 

Thanks!

**Comment by bgruening** [comment]
If you don't do `mulled-build push` is should not push it right? The only contained and why we are using quay.io is that the DockerHub API had no way to create a repository automatically back in the time.

**Comment by pcm32** [comment]
Ok, this was based on my lack of understanding on how involucro was talking to docker go libs and having not being able to achieve the whole process succesfully. I see now that mulled-build creates a docker image that you can see locally, so from there is simple. Thanks!
