### ISSUE TITLE
Include galaxy/tools/xsd/ ?

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy-lib#131]
What about adding https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/tools/xsd/ in `galaxy/tools/` ? Then we can remove `planemo/xml/xsd/tool/galaxy.xsd` from planemo.

**Comment by jmchilton** [comment]
Sure, good idea I think. Could pip upgrade galaxy-lib to get a new definition without requiring a Planemo update as well.

**Comment by nsoranzo** [comment]
I may give it a stab, thanks for the reply!

**Comment by jmchilton** [comment]
I'll do it - you assigned me ;). Give me a second.

**Comment by nsoranzo** [comment]
That was for having an answer :laughing: , but you surely know better the synchronisation tricks between this repo and galaxy.

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy-lib/pull/133 .
