### ISSUE TITLE
Readthedocs

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/galaxy-lib#3]
Just a minor issue, but the Documentation link to readthedocs is empty (just click it on the main README page).

**Comment by martenson** [comment]
I assume it is the similar reason as the main galaxyproject/galaxy has (readthedocs build timeout) so we will probably host the docs of this independently.

Thanks for the issue @tiagoantao

**Comment by martenson** [comment]
works now, thanks @tiagoantao !

**Comment by martenson** [comment]
https://galaxy-lib.readthedocs.io/en/latest/
