### ISSUE TITLE
Problematic imports in util/path/__init__.py on Windows

### ISSUE THREAD

**Issue by edwardsnj** [galaxyproject/galaxy-lib#96]
In a recent (?) release of this library, new imports were added to util/path/__init__.py that are problematic on Windows. The galaxy-lib module is used by pulsar on Windows, and these imports force an unhandled exception. The problematic imports are:

    from grp import getgrpid

and

    from pwd import getpwuid

Commenting these out restores pulsar functionality. 

These could by masked by a try/except ImportError/pass block.

Thanks,

- n

**Comment by jmchilton** [comment]
Thanks so much for the detailed report. I pushed a new release with the fix (#98). I don't have a Windows box to test this on - want to let me know if everything is better?

**Comment by edwardsnj** [comment]
Yes, that works for me.
